import { describe, it, expect, vi } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

// resolveTicker hits PocketBase + Yahoo; stub it to echo the broker symbol so
// the parser is tested in isolation (resolution has its own unit test).
vi.mock('../../src/importers/resolveTicker', () => ({
  resolveTicker: vi.fn(async (_isin: string, brokerSymbol: string) => brokerSymbol),
}));

import { Trading212PdfImporter } from '../../src/importers/trading212';

const HERE = dirname(fileURLToPath(import.meta.url));
const FIXTURE = join(HERE, '..', 'fixtures', 't212-synthetic.pdf');

describe('Trading212PdfImporter', () => {
  const importer = new Trading212PdfImporter();

  it('detects a Trading 212 activity statement', () => {
    expect(importer.detect('Generated by Trading 212 EU GmbH ... Activity statement')).toBe(true);
    expect(importer.detect('Revolut Account Statement')).toBe(false);
  });

  it('parses the open-positions table with cost basis = qty × avg price', async () => {
    const buf = readFileSync(FIXTURE);
    const { source, positions } = await importer.parse(buf);

    expect(source).toBe('trading212');
    // Fixture has exactly 4 positions; the decoy "Pending orders" table and the
    // following cash-breakdown section must NOT contribute rows.
    expect(positions).toHaveLength(4);

    const aapl = positions.find((p) => p.ticker === 'AAPL');
    expect(aapl).toBeDefined();
    expect(aapl!.isin).toBe('US0378331005');
    expect(aapl!.quantity).toBeCloseTo(3.5, 6);
    expect(aapl!.cost_basis).toBeCloseTo(3.5 * 150, 4); // 525
    expect(aapl!.cost_currency).toBe('USD');

    // ETF row (SGLN, GBX/pence listing) parses with cost basis too — and pence
    // is normalised to GBP (÷100): 10 × 5000 GBX = 50000 GBX → 500 GBP.
    const sgln = positions.find((p) => p.ticker === 'SGLN');
    expect(sgln).toBeDefined();
    expect(sgln!.cost_basis).toBeCloseTo(10 * 50, 2); // 500 GBP
    expect(sgln!.cost_currency).toBe('GBP');

    // Every position carries a non-undefined cost basis (T212 invariant).
    for (const p of positions) {
      expect(p.cost_basis).toBeTypeOf('number');
      expect(p.cost_basis).toBeGreaterThan(0);
    }
  });
});
