// Synthetic statement-PDF generator (Task 6.0/6.2/6.3 fixtures).
//
// PII POLICY: the user's REAL broker statements contain their name, address and
// account numbers and MUST NOT be committed. We instead generate SYNTHETIC PDFs
// with entirely FAKE personal data (fake name, fake account numbers) but in the
// SAME table layout and at the SAME column x-coordinates as the real exports
// (calibrated by inspecting the real PDFs locally). The importer is verified
// against BOTH the real (local, uncommitted) and these synthetic (committed)
// PDFs so the parser is layout-driven, not overfit to one file.
//
// The tickers/ISINs below are real, ISIN-valid instruments (so ISIN resolution
// stays meaningful) but the quantities/prices are fabricated.
//
// Run: `pnpm --filter finance-tracker-server tsx tests/fixtures/generate-pdfs.ts`
// (or `pnpm exec tsx ...`). Commits the two .pdf outputs next to this script.

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { PDFDocument, StandardFonts, type PDFFont, type PDFPage } from 'pdf-lib';

const HERE = dirname(fileURLToPath(import.meta.url));

// pdf-lib's y origin is bottom-left (same as pdf.js user-space), so the y values
// here map directly to the coordinates the parser reads back. The real T212
// statement is a wide landscape page whose right-most columns sit near x=813, so
// the page MUST be wider than that or pdf-lib silently clips off-page text.
const PAGE_W = 850; // wide enough for the right-most VALUE (EUR) column (~x=813)
const PAGE_H = 842;
const FONT_SIZE = 7;

function draw(page: PDFPage, font: PDFFont, str: string, x: number, y: number) {
  page.drawText(str, { x, y, size: FONT_SIZE, font });
}

// ===========================================================================
// Trading 212 — "Invest account - open positions summary"
// Columns (x anchors calibrated from the real statement):
//   INSTRUMENT 18 | ISIN 220 | INSTRUMENT CURRENCY 298 | QUANTITY 360 |
//   AVERAGE PRICE 420 | PRICE 489 | RETURN 556 | VALUE 614 | FX RATE 680 |
//   RETURN(EUR) 752 | VALUE(EUR) 800
// ===========================================================================

type T212Row = {
  instrument: string;
  isin: string;
  ccy: string;
  qty: string;
  avgPrice: string;
  price: string;
  ret: string;
  value: string;
  fx: string;
  retEur: string;
  valueEur: string;
};

// Fake quantities/prices; real, valid ISINs. Mixed currency incl. an ETF (SGLN)
// and a GBX listing to exercise currency handling.
const T212_ROWS: T212Row[] = [
  { instrument: 'AAPL', isin: 'US0378331005', ccy: 'USD', qty: '3.5', avgPrice: '150.00', price: '311.29', ret: '564.51', value: '1089.51', fx: '1.16118', retEur: '€486.16', valueEur: '€938.27' },
  { instrument: 'MSFT', isin: 'US5949181045', ccy: 'USD', qty: '2.0', avgPrice: '400.00', price: '427.36', ret: '54.72', value: '854.72', fx: '1.16118', retEur: '€47.13', valueEur: '€736.13' },
  { instrument: 'SGLN', isin: 'IE00B4ND3602', ccy: 'GBX', qty: '10.0', avgPrice: '5000.00', price: '6459.00', ret: '14590.00', value: '64590.00', fx: '86.506', retEur: '€168.66', valueEur: '€746.65' },
  { instrument: 'VUAA', isin: 'IE00BFMXXD54', ccy: 'USD', qty: '5.0', avgPrice: '130.00', price: '146.08', ret: '80.40', value: '730.40', fx: '1.16118', retEur: '€69.24', valueEur: '€629.01' },
];

async function buildT212(): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const page = pdf.addPage([PAGE_W, PAGE_H]);

  // --- detection markers + (FAKE) account header ---
  draw(page, font, 'CUSTOMER ID', 738, 572);
  draw(page, font, 'CUSTOMER NAME', 788, 572);
  draw(page, font, '99999999', 739, 564); // FAKE id
  draw(page, font, 'Test Investor', 785, 564); // FAKE name
  draw(page, font, 'Activity statement', 342, 514);
  draw(
    page,
    font,
    'Generated by Trading 212 EU GmbH on 5 June 2026, covering the statement period.',
    270,
    496,
  );

  // --- the import-target section + a DECOY "Pending orders" table above it ---
  draw(page, font, 'Invest account - open positions summary', 293, 460);

  // Decoy: "Pending orders" sub-table shares some header tokens but has ORDER ID
  // / TYPE / DIRECTION — the importer must target the OPEN-POSITIONS header, not
  // this one. (Real statements always carry this section, usually empty.)
  draw(page, font, 'Pending orders', 18, 440);
  const pendingHeader = [
    ['INSTRUMENT', 18], ['ISIN', 249], ['INSTRUMENT CURRENCY', 280],
    ['ORDER ID', 404], ['TYPE', 471], ['DIRECTION', 508], ['EXPIRATION', 566],
    ['QUANTITY', 632], ['LIMIT PRICE', 691], ['STOP PRICE', 750], ['VALUE', 813],
  ] as const;
  for (const [t, x] of pendingHeader) draw(page, font, t, x, 424);
  draw(page, font, 'No data available', 398, 408);

  // Open positions — the real header. (The two trailing RETURN/VALUE are the EUR
  // variants; that's how the real PDF labels them.)
  draw(page, font, 'Open positions', 18, 388);
  const header = [
    ['INSTRUMENT', 18], ['ISIN', 249], ['INSTRUMENT CURRENCY', 280],
    ['QUANTITY', 372], ['AVERAGE PRICE', 423], ['PRICE', 493], ['RETURN', 559],
    ['VALUE', 629], ['FX RATE', 683], ['RETURN', 760], ['VALUE', 813],
  ] as const;
  for (const [t, x] of header) draw(page, font, t, x, 372);

  // Data rows. Column x-anchors mirror the calibrated real positions.
  let y = 356;
  for (const r of T212_ROWS) {
    draw(page, font, r.instrument, 18, y);
    draw(page, font, r.isin, 220, y);
    draw(page, font, r.ccy, 298, y);
    draw(page, font, r.qty, 360, y);
    draw(page, font, r.avgPrice, 420, y);
    draw(page, font, r.price, 489, y);
    draw(page, font, r.ret, 556, y);
    draw(page, font, r.value, 614, y);
    draw(page, font, r.fx, 680, y);
    draw(page, font, r.retEur, 752, y);
    draw(page, font, r.valueEur, 800, y);
    y -= 16;
  }

  // Next section heading — the parser's terminator boundary.
  draw(page, font, 'Invest account - cash breakdown', 318, y - 16);
  draw(page, font, 'Total cash', 198, y - 34);

  return pdf.save();
}

// ===========================================================================
// Revolut — "USD Portfolio breakdown"
// Columns (x anchors calibrated from the real statement):
//   Symbol 60 | Company 97 | ISIN 194 | Quantity 275 | Price 341 |
//   Value 396 | % of Portfolio 496
// Terminator: "Positions Value".
// ===========================================================================

type RevRow = {
  symbol: string;
  company: string;
  isin: string;
  qty: string;
  price: string;
  value: string;
  pct: string;
};

const REVOLUT_ROWS: RevRow[] = [
  { symbol: 'META', company: 'Meta Platforms', isin: 'US30303M1027', qty: '2.48828342', price: 'US$593', value: 'US$1,475.55', pct: '24.7%' },
  { symbol: 'NVDA', company: 'NVIDIA', isin: 'US67066G1040', qty: '9', price: 'US$205.10', value: 'US$1,845.90', pct: '30.9%' },
  { symbol: 'AMZN', company: 'Amazon', isin: 'US0231351067', qty: '7.85401186', price: 'US$246.03', value: 'US$1,932.32', pct: '32.4%' },
  { symbol: 'CLNE', company: 'Clean Energy Fuels', isin: 'US1844991018', qty: '14.7601476', price: 'US$1.93', value: 'US$28.49', pct: '0.5%' },
  { symbol: 'NKE', company: 'Nike', isin: 'US6541061031', qty: '20.84188463', price: 'US$42.98', value: 'US$895.78', pct: '11.5%' },
];

async function buildRevolut(): Promise<Uint8Array> {
  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const page = pdf.addPage([PAGE_W, PAGE_H]);

  // --- detection markers + (FAKE) account header ---
  draw(page, font, 'Account Statement', 397, 774);
  draw(page, font, 'Generated on the 06 Jun 2026', 449, 762);
  draw(page, font, 'Test Investor', 60, 724); // FAKE name
  draw(page, font, 'Account number', 298, 690);
  draw(page, font, '00000000', 356, 690); // FAKE account number
  // "Revolut" only appears in the transaction descriptions in the real PDF; we
  // include the issuing-entity line so detect() (which scans the whole doc) sees
  // the brand the same way it does in production.
  draw(page, font, 'Revolut Securities Europe UAB', 60, 670);

  draw(page, font, 'USD Account summary', 60, 646);
  draw(page, font, 'Positions Value', 60, 618);
  draw(page, font, 'US$6,178.04', 258, 618);

  // --- the import-target table ---
  draw(page, font, 'USD Portfolio breakdown', 60, 542);
  const header = [
    ['Symbol', 60], ['Company', 97], ['ISIN', 194], ['Quantity', 275],
    ['Price', 341], ['Value', 396], ['% of Portfolio', 496],
  ] as const;
  for (const [t, x] of header) draw(page, font, t, x, 528);

  let y = 512;
  for (const r of REVOLUT_ROWS) {
    draw(page, font, r.symbol, 60, y);
    draw(page, font, r.company, 97, y);
    draw(page, font, r.isin, 194, y);
    draw(page, font, r.qty, 275, y);
    draw(page, font, r.price, 341, y);
    draw(page, font, r.value, 396, y);
    draw(page, font, r.pct, 496, y);
    y -= 14;
  }

  // Terminator + the transactions section that must NOT be parsed as holdings.
  draw(page, font, 'Positions Value', 60, y);
  draw(page, font, 'US$6,178.04', 396, y);
  draw(page, font, 'Total', 60, y - 14);
  draw(page, font, 'USD Transactions', 60, y - 44);
  const txHeader = [
    ['Date', 60], ['Symbol', 137], ['Type', 200], ['Quantity', 347],
    ['Price', 387], ['Side', 423], ['Value', 460], ['Fees', 476],
  ] as const;
  for (const [t, x] of txHeader) draw(page, font, t, x, y - 58);
  // A decoy transaction row with an ISIN-shaped-ish symbol to prove we stopped.
  draw(page, font, '16 Jul 2021 13:30:52 GMT', 60, y - 72);
  draw(page, font, 'XOM', 137, y - 72);
  draw(page, font, 'Trade - Market', 200, y - 72);
  draw(page, font, '1.68976005', 347, y - 72);

  return pdf.save();
}

async function main() {
  const t212 = await buildT212();
  writeFileSync(join(HERE, 't212-synthetic.pdf'), t212);
  const revolut = await buildRevolut();
  writeFileSync(join(HERE, 'revolut-synthetic.pdf'), revolut);
  // eslint-disable-next-line no-console
  console.log('Wrote t212-synthetic.pdf and revolut-synthetic.pdf');
}

main().catch((err) => {
  // eslint-disable-next-line no-console
  console.error(err);
  process.exit(1);
});
